In [1]:
l1=[34,43,54,34,48]
l1

[34, 43, 54, 34, 43]

In [6]:
l1_new=[]
for i in l1:
    l1_new.append(i+2)
l1_new


[36, 45, 56, 36, 45]

In [2]:
import numpy as np

In [8]:
a1 = np.array([34,43,54,34,48])
a1

array([34, 43, 54, 34, 48])

In [9]:
a1+2

array([36, 45, 56, 36, 50])

In [10]:
a2 = np.array([12,56.43,True,"as"])
a2

array(['12', '56.43', 'True', 'as'], dtype='<U32')

In [11]:
a2 = np.array([12,56.84,True])
a2

array([12.  , 56.84,  1.  ])

In [ ]:
What is numpy?
It is used for performing operation like array
addition,substraction,multipication, to ceate
some random numbers, create dummy values etc

List Vs Array
1. In list we cannot do element- wise operation but in array we can
2. Array to list converstion is possible and also List to array conversion
it also possible but will lose the dimensions
3. List is hetrogenous datatype but Numpy is a homogenous datatype.

In [13]:
arr1 = np.array([[2,5,8,0],[1,4,6,9]])
arr1

array([[2, 5, 8, 0],
       [1, 4, 6, 9]])

In [14]:
arr1.shape  #number of rows and column

(2, 4)

In [15]:
arr1.size #no of element

8

In [16]:
arr1.ndim  #dimensional number

2

In [18]:
arr1.dtype  # datatype of element

dtype('int64')

In [20]:
type(arr1) #data type

numpy.ndarray

In [23]:
tl1 =list(arr1)  # array to list
tl1

[array([2, 5, 8, 0]), array([1, 4, 6, 9])]

In [25]:
farr = arr1.flatten()
farr

array([2, 5, 8, 0, 1, 4, 6, 9])

In [24]:
tarr1 = np.array(tl1)  # list to array
tarr1

array([[2, 5, 8, 0],
       [1, 4, 6, 9]])

In [29]:
np.array(list(farr))

array([2, 5, 8, 0, 1, 4, 6, 9])

In [26]:
!git add .

In [27]:
!git commit -m "numpy"

[main feded0c] numpy
 4 files changed, 3351 insertions(+), 206 deletions(-)
 create mode 100644 .ipynb_checkpoints/numpy-checkpoint.ipynb
 create mode 100644 numpy.ipynb


In [28]:
!git push

To https://github.com/aryanra419/Python-class-notes
   64845f3..feded0c  main -> main


In [34]:
x= np.array([[23,33],[33,4]])
x


array([[23, 33],
       [33,  4]])

In [35]:
y = np.array([[43,2],[3,4]])
y

array([[43,  2],
       [ 3,  4]])

In [43]:
np.matmul(x,y)  # Matrix Multiplication

array([[1088,  178],
       [1431,   82]])

In [39]:
s=x+y
s

array([[66, 35],
       [36,  8]])

In [40]:
x*y

array([[989,  66],
       [ 99,  16]])

In [41]:
x-y

array([[-20,  31],
       [ 30,   0]])

In [42]:
x/y

array([[ 0.53488372, 16.5       ],
       [11.        ,  1.        ]])

In [47]:
#Create one 6X4 array

ar2=np.array([[23,4,3,2],[3,5,5,4],[3,4,5,3],[34,5,7,8],[3,5,3,5],[34,4,3,5]])
ar2

array([[23,  4,  3,  2],
       [ 3,  5,  5,  4],
       [ 3,  4,  5,  3],
       [34,  5,  7,  8],
       [ 3,  5,  3,  5],
       [34,  4,  3,  5]])

In [48]:
ar2.size

24

In [49]:
ar2.reshape(3,8)

array([[23,  4,  3,  2,  3,  5,  5,  4],
       [ 3,  4,  5,  3, 34,  5,  7,  8],
       [ 3,  5,  3,  5, 34,  4,  3,  5]])

In [50]:
ar2.reshape(8,3)

array([[23,  4,  3],
       [ 2,  3,  5],
       [ 5,  4,  3],
       [ 4,  5,  3],
       [34,  5,  7],
       [ 8,  3,  5],
       [ 3,  5, 34],
       [ 4,  3,  5]])

In [54]:
ar2.reshape(12,2)

array([[23,  4],
       [ 3,  2],
       [ 3,  5],
       [ 5,  4],
       [ 3,  4],
       [ 5,  3],
       [34,  5],
       [ 7,  8],
       [ 3,  5],
       [ 3,  5],
       [34,  4],
       [ 3,  5]])

In [55]:
ar2.reshape(4,6)

array([[23,  4,  3,  2,  3,  5],
       [ 5,  4,  3,  4,  5,  3],
       [34,  5,  7,  8,  3,  5],
       [ 3,  5, 34,  4,  3,  5]])

In [56]:
!git add .8

In [57]:
!git commit -m "numpy function"

[main 3b84f43] numpy function
 1 file changed, 373 insertions(+), 1 deletion(-)


In [58]:
!git push

To https://github.com/aryanra419/Python-class-notes
   feded0c..3b84f43  main -> main


In [4]:
d1=np.array([[2,8,9,5],[1,4,6,0],[3,2,7,1]])
d1

array([[2, 8, 9, 5],
       [1, 4, 6, 0],
       [3, 2, 7, 1]])

In [5]:
d1[1,2]

np.int64(6)

In [8]:
d1[0:2,0:2]

array([[2, 8],
       [1, 4]])

In [9]:
d1[1:3,1:3]

array([[4, 6],
       [2, 7]])

In [12]:
d1[1:,2:]

array([[6, 0],
       [7, 1]])

In [14]:
# extract even row index and odd column index

d1[::2,1::2]

array([[8, 5],
       [2, 1]])

In [15]:
#reverse the matrix

d1[::-1,::-1]

array([[1, 7, 2, 3],
       [0, 6, 4, 1],
       [5, 9, 8, 2]])

In [17]:
#create a numpy array with numbers from 10 to 50

np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [20]:
# create 3X3 zero matrix

np.zeros((3,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [22]:
# create 5X5 identity matrix

np.identity(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [23]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [27]:
#for d1 matrix calculate sum,mean,standard deviation,max,min

d1.sum()

np.int64(48)

In [28]:
d1.min()

np.int64(0)

In [32]:
d1.mean()

np.float64(4.0)

In [33]:
d1.std()

np.float64(2.857738033247041)

In [30]:
d1.max()

np.int64(9)

In [31]:
d1.min()

np.int64(0)