In [1]:
l1=[34,43,54,34,48]
l1

[34, 43, 54, 34, 43]

In [6]:
l1_new=[]
for i in l1:
    l1_new.append(i+2)
l1_new


[36, 45, 56, 36, 45]

In [7]:
import numpy as np

In [8]:
a1 = np.array([34,43,54,34,48])
a1

array([34, 43, 54, 34, 48])

In [9]:
a1+2

array([36, 45, 56, 36, 50])

In [10]:
a2 = np.array([12,56.43,True,"as"])
a2

array(['12', '56.43', 'True', 'as'], dtype='<U32')

In [11]:
a2 = np.array([12,56.84,True])
a2

array([12.  , 56.84,  1.  ])

In [ ]:
What is numpy?
It is used for performing operation like array
addition,substraction,multipication, to ceate
some random numbers, create dummy values etc

List Vs Array
1. In list we cannot do element- wise operation but in array we can
2. Array to list converstion is possible and also List to array conversion
it also possible but will lose the dimensions
3. List is hetrogenous datatype but Numpy is a homogenous datatype.

In [13]:
arr1 = np.array([[2,5,8,0],[1,4,6,9]])
arr1

array([[2, 5, 8, 0],
       [1, 4, 6, 9]])

In [14]:
arr1.shape  #number of rows and column

(2, 4)

In [15]:
arr1.size #no of element

8

In [16]:
arr1.ndim  #dimensional number

2

In [18]:
arr1.dtype  # datatype of element

dtype('int64')

In [20]:
type(arr1) #data type

numpy.ndarray

In [23]:
tl1 =list(arr1)  # array to list
tl1

[array([2, 5, 8, 0]), array([1, 4, 6, 9])]

In [25]:
farr = arr1.flatten()
farr

array([2, 5, 8, 0, 1, 4, 6, 9])

In [24]:
tarr1 = np.array(tl1)  # list to array
tarr1

array([[2, 5, 8, 0],
       [1, 4, 6, 9]])